### ISSUE TITLE
No files found to lint

### ISSUE THREAD

**Issue by skyfremen** [rich-newman/typescript-analyzer#13]
![nofileslint](https://user-images.githubusercontent.com/22805288/27938405-7b7f5eba-62f0-11e7-84ce-81342df86805.JPG)

The .ts file will not be detected if it is nested behind an .html file
It will "show no files found to lint"

**Comment by rich-newman** [comment]
Please go to Tools/Options/TypeScript Analyzer and then change the setting 'Ignore nested files' to false.

Your nested files should then be included.

**Comment by skyfremen** [comment]
Thanks for informing, it is working now.
