### ISSUE TITLE
errors when codelyzer is in project

### ISSUE THREAD

**Issue by zewpo** [rich-newman/typescript-analyzer#16]
Hi Rich,

Thanks for this project, it fits what I need.  

This issue is about codelyzer.

My project team use codelyzer, and include this at the top of our shared tslint.json;

`
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
...
`
This works fine in atom, and in VS Code.  I'd like it to work in VS, and have TSLinting work like this TypeScript Analyzer provides.  But, this codelyzer bit is making TypeScript Analyzer fail.

Do you think TypeScript Analyzer can be made to work when codelyzer is in the mix?  

I'll try and make it work - although may need some help - this will be my first bash at VS Plugins.  Will postback any progress I make.  If someone else can make it work, would be great too.

Many Thanks,

Chris Plewright.

**Comment by rich-newman** [comment]
@zewpo I'm not a codelyzer expert, but we had an issue (#8) relating to it before.  At the time codelyzer was incompatible with the latest versions of tslint.  To get it working I had to do a build of the analyzer with an old version of tslint, but the issue was resolved with codelyzer 3.x.  That is, at the time codelyzer 3.x was working with the analyzer.

So it may well be a JS dependency hell issue: I can have a look if you're not getting anywhere?

**Comment by zewpo** [comment]
@rich-newman yes, the problem I experienced was related to the version of codelyzer at first - sorry I didnt see issue #8 earlier.   So, I tried to upgrade codelyzer.  But then this;  Warning: The 'no-use-before-declare' rule requires type infomation.

I ended up modifying LinterBase.cs.   By adding in a local Process call to "ng lint" which I believe uses the projects own environment.  I think its a bit hacky though, because it doesnt use the external nodejs server approach that WebAnalyzer uses, it doesnt quite fit into the same pattern.  

Anyway, I'm happy it is working for me now.   I'll upload my change so you can see what I've done.

[https://github.com/zewpo/typescript-analyzer/blob/master/src/WebLinter/Linting/Linters/LinterBase.cs](https://github.com/zewpo/typescript-analyzer/blob/master/src/WebLinter/Linting/Linters/LinterBase.cs)

**Comment by karrijreddy** [comment]
HI rich,
currently using typescript analyser in VS2017 with no issues. all working fine (thanks :) ).
But i am now trying to inlcude Codelyser as well . i have included the rules directory in the tslint.json & added codelyser rules to the existing rules., 
{ "rulesDirectory": [ "node_modules/codelyzer" ], "rules": { ...}
but nothing seems to happen. only the typescript analyser related errors are shown in the errors list. I dont get any errors regarding codelyser as well. i am using all the latest versions as on today. 

do i need to do anything else to make this work?

**Comment by rich-newman** [comment]
Hi @karrijreddy - I don't think you should need to do anything else, although I haven't tried with the latest versions.  I did get it working with earlier versions.  Have a look at issue #8 if you haven't already: I was using the tslint.jsons in there and there's even a screenshot of it working.  Let me know if you're still stuck: I want this thing to work with codelyzer if possible.

**Comment by karrijreddy** [comment]
hi rich,
Thanks for a response. Its working now :) .. all i did was uninstall & reinstall tsanalyser and it started showing errors from codelyser as well.
One minor usage issue i see now is that the links on the error codes(coming from codelyser) point to tslint urls which will be invalid(which is understandable). 
Do you think its possible to point to the codelyser urls for those error code? as u see in attached image.

![image](https://user-images.githubusercontent.com/30897925/29209617-195c26c2-7ead-11e7-807e-337d718daf2a.png)

**Comment by zewpo** [comment]
Hi @karrijreddy  and @rich-newman ,
I've just done my first Pull Request.  Yay!.  anyway, for codelyzer support, it picks up some of the codelyzer URL patterns - although the samples I had use the goo.gl pattern, rather than the extended angular.io pattern.  So, it may not catch all of them ?!.  Also, I made it able to use local ng lint, so it now solves issue #8 without needing to make breaking changes to ones project.  For caution, I only allow enabled local ng lint as an optional setting that is off be default - because its not really fast.  But at least it works for older projects - by default it will work as per the external node.js server way of doing it.

**Comment by rich-newman** [comment]
@zewpo and @karrijreddy 
zewpo's changes have now been released in version 1.9.  The URLs for codelyzer should now be picked up.  I extended what Chris had done so it worked with angular.io URLs as well.  The local ng lint stuff is in there too.

**Comment by zewpo** [comment]
Thanks @rich-newman, 

That's great. I like your description of the update in the README.md. 

I've been thinking about when local 'ng lint' fails, falling back to the default plugin linting - and there's no notification to the user.   It may end up using different linting rules than the user expects!   Technically the user's configuration needs fixing but they wouldn't know.  So, for that reason,  it would be proper to fail with an exception instead of falling back.  I had put the try-catch in originally  not wanting to break the plugin with my changes, but I now think the try-catch is potentially hiding important information.  Sorry about that.  So we could remove it and solve that problem.  The user should be able to see the exception message in the plugin's output window, informing them to fix their configuration.   

Can I leave that with you, instead of doing another Pull Request?  

Apart from that, I think this issue #16 is resolved, and I'll close it out. 

Cheers, 
Chris Plewright
