### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by ghost** [rich-newman/typescript-analyzer#17]
Installed this extension and getting a "NullReferenceException", so this needs to be here.

The following is from the Visual Studio 2017 Output view:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebLinterVsix.TableDataSource.CreateFileNameToProjectNameMap() in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 142
   at WebLinterVsix.TableDataSource.AddErrors(IEnumerable`1 errors) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 121
   at WebLinterVsix.ErrorListService.ProcessLintingResults(IEnumerable`1 results, String[] fileNames, String[] filterFileNames, Boolean showErrorList) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\ErrorListService.cs:line 20
   at WebLinterVsix.LinterService.<Lint>d__3.MoveNext() in C:\Source\typescript-analyzer2\src\WebLinterVsix\LinterService.cs:line 32
```

**Comment by rich-newman** [comment]
@Droritos Can you tell me what sort of project you are trying to analyze, or, better, upload it somewhere please?  Or is it any project?

**Comment by ghost** [comment]
@rich-newman, it's a private "Blank Node.js Web Application" which I've changed to hold a vue.js SPA website. Everything works besides this plugin.

Recently I've installed TypeScript 2.4 using [TypeScript SDK](https://www.microsoft.com/en-us/download/details.aspx?id=55258), I don't know if it's related.

Attached my configuration.
![tslint](https://user-images.githubusercontent.com/13335376/28997643-3083b4ee-7a22-11e7-8690-0e1c82331191.PNG)

**Comment by rich-newman** [comment]
OK, I had a quick look this afternoon.  That code is iterating the projects so it can map returned linting errors to the associated project name.  I don't have very good defense around it: if it throws it's likely to display no linting errors at all.  Also I get a similar error (although not exactly the same) if I have an unloaded project along with a loaded one in my solution and then run for the entire solution.  That's just a bug: you don't have an unloaded project by any chance?

I've fixed the bug and added some better error handling which should theoretically mean you don't get project names but do get to see the linting errors.  I will release that, probably early next week now.

**Comment by rich-newman** [comment]
@Droritos I've done a release, 1.8.  I'm not sure if it will fix your problem, but it may give more of a clue as to what the problem is.  Perhaps you can try again with your troublesome project when you get a moment please?

**Comment by ghost** [comment]
It works! Thank you!!

**Comment by rich-newman** [comment]
Awesome
