### ISSUE TITLE
Build continues even when errors are displayed in the error window.

### ISSUE THREAD

**Issue by padmadighe** [rich-newman/typescript-analyzer#19]
Build continues even when errors are displayed in the error window with the latest version of typescript analyzer.

**Comment by rich-newman** [comment]
@padmadighe I'm not seeing this.  My builds fail if there are errors with and without 'Use tsconfig.json files' and with and without the new 'Use local ng lint' option.  There really isn't anything in the last release that should affect this.  Can you give some more information?  Which options are you using?

**Comment by padmadighe** [comment]
hi rich,
it was working in 1.5 release (last know).. & i have checked it on 1.8 & latest version now & it isn't working. 
Attached options screen below:
![image](https://user-images.githubusercontent.com/29100295/29407097-d77cc60e-8360-11e7-84fe-b46ce8d264e8.png)
dependency versions we r using is : 
"devDependencies": {
    "@angular/cli": "^1.0.3",
    "@angular/compiler-cli": "^4.3.3",
    "@types/node": "~6.0.60",
    "codelyzer": "^3.1.2",
    "ts-node": "~2.0.0",
    "tslint": "^5.6.0",
    "typescript": "~2.2.0"}

also attaching the issue screen shot .
![image](https://user-images.githubusercontent.com/29100295/29407593-81cd9a24-8362-11e7-90c9-84e6410c12ff.png)

please let me know if u need more info?

**Comment by rich-newman** [comment]
I've replicated the problem using your sample app from issue #7 and putting in the package.json changes you show.  We do have a bug in the new 'use local ng lint' option if you're trying to stop a build because of tslint errors.  We'll fix it.

However, you don't need to use the new option if you're using codelyzer 3.1.  It's only needed if you're using a version of codelyzer less than 3.0. 

For me, in the sample app above I get the same errors if I turn 'use local ng lint' to false.  It runs more quickly and it DOES stop a build correctly. 

Does it work if you just turn 'use local ng lint' to false?

**Comment by padmadighe** [comment]
hi rich,
it is not working for any option. 
Also i now am not able to see any of the codelyzer issues in the error window (which was working before). i can only see tslint issues :( , but only if i open the file , then i see the codelyzer error. 
![image](https://user-images.githubusercontent.com/29100295/29548948-878ceb4a-8722-11e7-9e3d-9694b4acc7c3.png)

i am getting the below error in output window:
tslint Output: Your global Angular CLI version (1.2.7) is greater than your local
version (1.0.3). The local Angular CLI version is used.
Parsing Exception: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.

i haven't made any changes except that i restarted  my machine.

**Comment by rich-newman** [comment]
Errors like that can be caused when you are trying to use codelyzer locally with the main analyzer and have a version mismatch between the versions of tslint and typescript that the analyzer use (currently tslint 5.6.0 and typescript 2.4.2) and the version in your angular CLI install.

This is why @zewpo added the local call to ng lint, which should get rid of these errors.  All it does is issue the ng lint command from a command prompt and get the analyzer to interpret the results.  So if 'ng lint' works in your project it should work.  When I get a moment I'm going to have a look at a more robust solution though.

In the meantime I have released version 1.10 of the analyzer, and this fixes the bug with the 'Use local ng lint' option when trying to stop a build with codelyzer errors.  It also shows some very limited output in the TypeScript Analyzer Output window when this option is set and you try to run the analyzer.

Can you try taking the new release and running it with 'Use local ng lint' set to true please?

**Comment by rich-newman** [comment]
By the way, I don't think the error that starts '[tslint]' in the error window is coming from the analyzer: all of our errors start '(TSLint)'.

**Comment by rich-newman** [comment]
@padmadighe Is this resolved now?

**Comment by padmadighe** [comment]
Yes it is.

Thanks
Padma


Padma Dighe
Sr. Advisory Software Engineer
Kofax India Private Limited

The V, Capella Block 6th Floor, Plot No17, Software Units Layout, Madhapur
Hyderabad, 500 081
INDIA

Tel: +91 40 45459949
Fax: +91 40 45459922
Padma.Dighe@kofax.com

blog<http://www.kofax.com/blog/> | twitter<https://twitter.com/Kofax> | linkedin<https://www.linkedin.com/company/kofax> | facebook<https://www.facebook.com/kofax.inc> | talent network<http://www.jobs.net/jobs/Kofax-Inc/join>
