### ISSUE TITLE
Erros are not shown withing code editor

### ISSUE THREAD

**Issue by vladimir-djokic** [rich-newman/typescript-analyzer#2]
If there are **tslint** errors present in the `Error List` panel, no error is shown in code editor. It would be great if **Typescript Analyzer** could be extended to show errors in code editor as well (thus, showing wavy red underlines).

**Comment by vladimir-djokic** [comment]
If you don't have the time I can investigate implementation details/requirements?

**Comment by vladimir-djokic** [comment]
An early (**very rough**) standalone prototype:

![tslint](https://vladeck.files.wordpress.com/2017/05/tslint.png)

Implemented by using concept of tags in **Visual Studio 2017**. Still very new to me, but it feels like it would be possible to _"plug"_ the extension code so that the tags are created/redrawn by **Visual Studio** whenever extensions finishes with its linter run. It is also possible to control the type of tag, such as **error**, **warning**, ... based on the results of linting.

**Comment by rich-newman** [comment]
Thanks @vladeck that looks good.  This was on the roadmap for the original project, although the aim of this project was really just to have an upgraded version and not worry about enhancing it too much.  If you have time I'm happy to take a pull request though.  The tagging looks like the right way to go based on my very limited knowledge of this.

**Comment by ghost** [comment]
@vladeck Are you still working on this feature? I just saw your own project https://github.com/vladeck/TSLint/tree/master/TSLint and am wondering if it is a complete re-build of this typescript-analyzer. It would be awesome if you could just merge your squiggle feature into this project. I can act as spokesman for @rich-newman, he is very fast in reviewing, enhancing, and applying pull requests. If you send a PR your work will soon be available to many users!

**Comment by vladimir-djokic** [comment]
@rich-newman With `typescript-tslint-plugin` already working with Visual Studio 2017 and improving day-by-day, I believe you can close this issue. I already put notice on my own project and I'm glad that we now have official support for this :)
