### ISSUE TITLE
No Errors were listed after the build

### ISSUE THREAD

**Issue by Bhimisetty** [rich-newman/typescript-analyzer#28]
I am running Visual Studio 2017, Version 15.5.1. I have this plugin installed and there are zero errors reported when I build my solution/Project. But i got the error list when i ran the "Run TypeSrcipt Analyzer" from right click of the project. The following is configured for the Analyzer. I have my own tslint.json file in the root folder of the project.
![capture](https://user-images.githubusercontent.com/9347559/38615088-12bde2fa-3dad-11e8-986a-aabc0a19a851.PNG). 
Do i miss anything to show the errors in the error window and to stop the build if any error found?

**Comment by rich-newman** [comment]
You're not doing anything obviously wrong, and that should work.  In fact it works for me with 'Use local ng lint' set to True and a standard Angular CLI solution.

That 'Use local ng lint' is relying on your local configuration and expects an Angular CLI project or similar: is that what you meant to do?

If so there are a couple of things that will give us more information:
- The Visual Studio Output window should hopefully have a 'TypeScript Analyzer' entry in the dropdown after you've done a build and nothing's happened.  If you select that it will show an error message if there is one, or that it thinks it succeeded if it didn't.
- Try starting a command prompt, navigating to the project folder (the one with the csproj in it) and doing 'ng lint'.  Does that work?

**Comment by eicthecat** [comment]
I don't know if it's related but on a friend's vs, in the output window for typescript analyzer, there is 'sometimes' an error message saying something went wrong on  line 91 of LinterFactory.cs -  (I will append the real message if you are interessed in) - I supposed there is some bug in removing the tmp directory or something like that, then... (sorry for this relatively unconsistent informations :-))
