### ISSUE TITLE
Default tslint.json has schema issues

### ISSUE THREAD

**Issue by rich-newman** [rich-newman/typescript-analyzer#29]
Open the default tslint.json in the Visual Studio editor and you get a message (in the Error List/Message):

_There are problems with this document's schema impacting one or more items in the document_	

Previously there were no such errors: I think the schema must have been updated.

**Comment by rich-newman** [comment]
It turns out that the [tslint.json schema](http://json.schemastore.org/tslint) in the json schema store has been invalid since 11th April 2018.  So this can't be fixed from the Analyzer.  I think the default tslint.json is still fine in fact.  I'll raise a PR against the store to fix it.

**Comment by rich-newman** [comment]
PR raised against Schema Store.  Closing as it's not an Analyzer issue.

**Comment by HolgerJeromin** [comment]
ref https://github.com/SchemaStore/schemastore/pull/487
