### ISSUE TITLE
Add command to run from current file

### ISSUE THREAD

**Issue by seangifford** [rich-newman/typescript-analyzer#36]
Right now, the analyzer can be run from the Solution Explorer, but not from the editor of the current file.
It would be convenient to have available in the editor, and it would facilitate integration into other tools.
For example, we are invoking the Fix command from CodeMaid during a Clean.  But that Fix command applies to the currently selected file in the Solution Explorer, not the editor, and so the file being cleaned is not necessarily the file that the Fix command is being run on.

**Comment by rich-newman** [comment]
I'm a little unsure what you're asking for: do you mean you want options on the editor context menu to run the Analyzer and fix?  So if you rightclick in the editor window you can fix straightaway without having to bring up Solution Explorer?  It sounds like it, but then how does that help with CodeMaid: how exactly are you invoking Fix from CodeMaid?
