### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by ttv86** [rich-newman/typescript-analyzer#37]
Is support for Visual Studio 2019 coming soon? Official release date of Visual Studio 2019 is within few weeks.

**Comment by rich-newman** [comment]
It is coming, but probably not 'soon'.  It may not be until May.  I'll update here when I have a better idea.

**Comment by jopuckman** [comment]
Just poking this thread to see if the May-ish estimate is still feasible.

**Comment by petehughes** [comment]
I'm sorry I have no idea what is about??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rich-newman** [comment]
@jopuckman Yes, it should be released in May, but not until the end of May. The work is done but I'm on vacation currently.

**Comment by jopuckman** [comment]
Excellent! Thank you

**Comment by rich-newman** [comment]
@jopuckman - Version 1.19 has now been released, which includes VS2019 support.  It should appear in the Online part of Extensions/Manage Extensions in VS2019 if you search for 'TypeScript Analyzer'.
