### ISSUE TITLE
Visual Studio 2022 update.

### ISSUE THREAD

**Issue by malylemire1** [rich-newman/typescript-analyzer#42]
Can you provide an update for VS2022?

Thanks

**Comment by rich-newman** [comment]
@malylemire1 This extension is based on TSLint, which has been [deprecated in favor of ESLint](https://www.npmjs.com/package/tslint) for some time.  As a result I have this week published new extensions based on ESLint, separately for [Visual Studio 2017/2019](https://marketplace.visualstudio.com/items?itemName=RichNewman.TypeScriptAnalyzerEslintPrettier2019) and for [Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=RichNewman.TypeScriptAnalyzerEslintPrettier).  These new extensions are (hopefully) better than the current one in many ways.  [See the readme for more details](https://github.com/rich-newman/typescript-analyzer).

As a result I don't intend to upgrade this extension to Visual Studio 2022.
