### ISSUE TITLE
Error shown in the Output window and no lint errors shown

### ISSUE THREAD

**Issue by davidsekar** [rich-newman/typescript-analyzer#8]
I see following error when I try to run the Typescript analyzer during build

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   at WebLinter.TsLintLinter.ParseErrors(String output) in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\TslintLinter.cs:line 17
   at WebLinter.LinterBase.<Lint>d__27.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterBase.<Run>d__26.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterFactory.<LintAsync>d__5.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\LinterFactory.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinterVsix.LinterService.<LintAsync>d__4.MoveNext() in C:\Source\typescript-analyzer\src\WebLinterVsix\LinterService.cs:line 67`

Tslint.json
`{
  "extends": [
    "tslint:recommended"
  ],
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "trailing-comma": [false, {"multiline": "always", "singleline": "never"}],
    "interface-name": [false, "always-prefix"],
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "import-destructuring-spacing": true,
    "invoke-injectable": true,
    "no-access-missing-member": true,
    "no-attribute-parameter-decorator": true,
    "no-forward-ref": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "pipe-naming": [true, "camelCase", "my"],
    "templates-use-public": true,
    "use-host-property-decorator": true,
    "use-input-property-decorator": true,
    "use-life-cycle-interface": true,
    "use-output-property-decorator": true,
    "use-pipe-transform-interface": true,
    "no-console": [true,
      "time",
      "timeEnd",
      "trace"
    ],
    "max-line-length": [
      true,
      100
    ],
    "no-string-literal": false,
    "no-use-before-declare": true,
    "object-literal-sort-keys": false,
    "ordered-imports": [ false ],
    "quotemark": [
      true,
      "single",
      "avoid-escape"
    ],
    "variable-name": [
      true,
      "allow-leading-underscore",
      "allow-pascal-case",
      "ban-keywords",
      "check-format"
    ]
  }
}`

**Comment by radomeit** [comment]
Hi, I'm getting the same error:

```
16.06.2017 09:57:54: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
   bei Newtonsoft.Json.JsonTextReader.ParseValue()
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   bei WebLinter.TsLintLinter.ParseErrors(String output) in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\TslintLinter.cs:Zeile 17.
   bei WebLinter.LinterBase.<Lint>d__27.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:Zeile 62.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WebLinter.LinterBase.<Run>d__26.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:Zeile 53.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WebLinter.LinterFactory.<LintAsync>d__5.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\LinterFactory.cs:Zeile 54.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WebLinterVsix.LinterService.<LintAsync>d__4.MoveNext() in C:\Source\typescript-analyzer\src\WebLinterVsix\LinterService.cs:Zeile 67.

```
using this tslint.json:

```
{
  "extends": [
    "tslint:recommended"
  ],
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    // Custom
    "trailing-comma": [
      false,
      {
        "multiline": "always",
        "singleline": "never"
      }
    ],
    "interface-name": [ false, "always-prefix" ],
    "component-class-suffix": true,
    "comment-format": [ false ],
    "component-selector": [ true, "element", "knd", "kebab-case" ],
    "directive-class-suffix": true,
    "directive-selector": [ true, "attribute", "knd", "camelCase" ],
    "import-destructuring-spacing": true,
    "invoke-injectable": true,
    "no-access-missing-member": false,
    "no-attribute-parameter-decorator": true,
    "no-forward-ref": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "one-line": [ false ],
    "pipe-naming": [ true, "camelCase", "knd" ],
    "prefer-for-of": false,
    "templates-use-public": true,
    "use-host-property-decorator": true,
    "use-input-property-decorator": true,
    "use-life-cycle-interface": true,
    "use-output-property-decorator": true,
    "use-pipe-transform-interface": true,
    "arrow-parens": false,
    // General
    "no-console": [
      true,
      "time",
      "timeEnd",
      "trace"
    ],
    "no-empty": false,
    "no-shadowed-variable": false,
    "max-line-length": [
      true,
      200
    ],
    "no-string-literal": false,
    "no-use-before-declare": true,
    "object-literal-sort-keys": false,
    "ordered-imports": [ false ],
    "quotemark": [ false ],
    "variable-name": [
      true,
      "allow-leading-underscore",
      "allow-pascal-case",
      "ban-keywords",
      "check-format"
    ]
  }
}

```

**Comment by rich-newman** [comment]
Unfortunately codelyzer is incompatible with the latest versions of tslint.  The TypeScript Analyzer uses tslint v5.4.2, codelyzer requires a tslint peer of v4.  Also my error handling sucks, but I'll sort that out for the next release.

I proved this by doing a build of the analyzer with v4.0.0 and ts v2.0.9, which is what the codelyzer readme uses.  The TypeScript Analyzer works with codelyzer (and your config above) if you do this.

You can do this yourself, but better would obviously be for codelyzer to be compatible with current versions of tslint.

**Comment by rich-newman** [comment]
Since I actually bothered to do it, here's the output from the rebuilt TypeScript Analyzer with the codelyzer readme component.ts:
![image](https://user-images.githubusercontent.com/17277125/27222498-5abac952-5284-11e7-8442-1bd06faa3b1f.png)

**Comment by radomeit** [comment]
Thanks. After upgrading to codelyzer 3.x (which supports tslint@5) the error is gone. 

I'm still having the problem that the tslint errors won't show up in my vs 2017 error list, but this can be a problem with my IDE settings which I'll check out later.

**Comment by rich-newman** [comment]
Closing as issue is resolved

**Comment by rich-newman** [comment]
Re my error handling sucking: version 1.5 now at least tells you what the output from tslint was if it can't be parsed.  This isn't necessarily helpful, tslint output isn't always great.  However it can give you a clue:

6/24/2017 7:39:30 PM: System.FormatException: Unable to parse output from tslint. List of linting errors is expected.
tslint Output: Failed to load C:\Users\Richard Newman\tslint.json: Could not find custom rule directory: node_modules/codelyzer
